name: Build BrushPlugin (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore BrushPluginExample\BrushPlugin.csproj

      - name: Build with MSBuild
        run: msbuild BrushPluginExample\BrushPlugin.csproj /p:Configuration=Release /p:Platform=x64

      - name: Package artifact
        uses: actions/upload-artifact@v4
        with:
          name: BrushPlugin-build
          path: BrushPluginExample\bin\Release
